services:
  app:
    build: .
    container_name: url-shortener-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/shortener_db
      - SPRING_DATASOURCE_USERNAME=haru
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      mariadb:
        condition: service_healthy

  mariadb:
    image: mariadb:latest
    container_name: shortener_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: shortener_db
      MYSQL_USER: haru
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
